apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterautoscaler-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::742020474734:role/clusterautoscalerpolicy