apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # Options: ClusterIP (default), NodePort, LoadBalancer
  selector:
    app: nginx    # Must match the labels defined under metadata.labels in your pod.yaml
  ports:
    - protocol: TCP
      port: 80         # Port exposed inside the cluster
      targetPort: 80   # Port the container listens on
      nodePort: 30007  # Optional: specify a port in range 30000-32767